name: CI-latest

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Composer    
        uses: php-actions/composer@v6
        with:
          php_version: "8.3"
          version: latest
       
      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: Poseidon
        with:
          version: 11.0
          php_version: 8.3
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
